version = 0.1

[default.deploy.parameters]
stack_name = "acmemodels-backend"
region = "us-east-2"

# Let SAM manage per-account artifact buckets automatically
resolve_s3 = true

# Capabilities
capabilities = "CAPABILITY_NAMED_IAM"

# CI quality-of-life: don't require interactive confirms
confirm_changeset = false

# Leave empty if youâ€™re not deploying container images
image_repositories = []
s3_prefix = "acmemodels-backend"
parameter_overrides = "ArtifactNameIndexTable=\"ArtifactNameIndex\""

[default.global.parameters]
region = "us-east-2"
